[version]
current = "2.1.0b3"

regex = '''
  (?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)((?P<prerelease>[a-z]+)(?P<build>\d+))?
  '''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "core/setup.py"
search = "package_version = '{current_version}'"

[[file]]
src = "core/sodasql/__version__.py"
search = "SODA_SQL_VERSION = '{current_version}'"

[[file]]
src = "packages/athena/setup.py"
search = "package_version = '{current_version}'"

[[file]]
src = "packages/bigquery/setup.py"
search = "package_version = '{current_version}'"

[[file]]
src = "packages/hive/setup.py"
search = "package_version = '{current_version}'"

[[file]]
src = "packages/postgresql/setup.py"
search = "package_version = '{current_version}'"

[[file]]
src = "packages/redshift/setup.py"
search = "package_version = '{current_version}'"

[[file]]
src = "packages/snowflake/setup.py"
search = "package_version = '{current_version}'"

[[file]]
src = "packages/sqlserver/setup.py"
search = "package_version = '{current_version}'"
